### ISSUE TITLE
Single Click Toggle for Day/Night

### ISSUE THREAD

**Issue by hassan987** [lswank/Tranquility#14]
It will be a good user interface improvement if we can toggle day/night by just clicking on the menubar icon. It will help every time the user needs to toggle and have a look at some graphic or image? A keyboard shortcut for day/night toggle could also be great!

**Comment by lswank** [comment]
I don't think I'll be adding the single click because it complicates the user interface too much. Also, Cocoa doesn't like to do that easily, and I'd rather go with the grain instead of against it. That said, I've added a keyboard shortcut (user changeable).

It is in the latest tag.

https://github.com/lswank/Tranquility/releases/tag/1.1
